#!/usr/bin/env node
/**
 * Regenerates API.md from the live router stack, so the documented endpoint
 * list cannot drift from the code.  Run: npm run docs
 */
const fs = require("fs");
const path = require("path");
const Module = require("module");

const adminStub = {
  apps: [{}], initializeApp: () => {}, credential: { cert: () => ({}) },
  firestore: () => ({}), storage: () => ({ bucket: () => ({}) }),
  auth: () => ({ verifyIdToken: async () => ({ uid: "u", role: "student" }) }),
};
const cfg = { apiKey:"s", authDomain:"s.firebaseapp.com", projectId:"stub-project",
              storageBucket:"s.appspot.com", messagingSenderId:"1", appId:"1:1:web:1" };
const origLoad = Module._load;
Module._load = function (req, parent, isMain) {
  if (req.indexOf("firebaseadminvar") !== -1)
    return { admin: adminStub, serviceAccount:{project_id:"stub"}, firebaseConfig: cfg,
             db:{}, auth: adminStub.auth(), bucket:{} };
  if (req === "firebase-admin") return adminStub;
  return origLoad.call(this, req, parent, isMain);
};
Object.assign(process.env, cfg, { key: "0".repeat(64), iv: "0".repeat(32) });

const GROUPS = [
  ["Courses & video", "/api", "../routes/videos"],
  ["Auth & users", "/api/auth", "../routes/user.routes"],
  ["Admin", "/api/admin", "../routes/admin.routes"],
  ["Dashboard", "/api/dashboard", "../routes/dashboard.routes"],
  ["Course content", "/api/course", "../routes/course.routes"],
  ["Gamification", "/api/gamification", "../routes/gamification.routes"],
  ["Roles & modules", "/api/roles", "../routes/roles_modules.routes"],
  ["Community", "/api/community", "../routes/community.routes"],
  ["Advertisements", "/api/advertisement", "../routes/advertisement.routes"],
  ["Students", "/api/students", "../routes/students.routes"],
  ["Announcements", "/api/announcements", "../routes/announcement.routes"],
  ["Payments", "/api/payment", "../routes/purchase.routes"],
  ["Certificates", "/api/certificates", "../routes/cert.routes"],
  ["Chat", "/api/chat", "../routes/chat.routes"],
];

const ANON = new Set([
  "POST /api/auth/register", "PATCH /api/auth/login", "POST /api/admin/login",
]);

let out = `# Excel Academy API

Generated by \`npm run docs\` from the Express router stack - do not edit by hand.

## Authentication

All clients sign in with **Firebase Auth**. The server verifies the Firebase ID
token; it does not issue its own session.

Send the token on every authenticated request:

\`\`\`
Authorization: Bearer <firebase id token>
\`\`\`

Obtain it client-side with:

| Client | Call |
| --- | --- |
| Flutter | \`await FirebaseAuth.instance.currentUser!.getIdToken()\` |
| Web (JS) | \`await getAuth().currentUser.getIdToken()\` |

A cookie named \`access_token\` is accepted as a fallback for browser clients.

### Access levels

| Level | Meaning |
| --- | --- |
| **Anonymous** | No token needed. |
| **Public** | No token needed; a token, if sent, is read (\`optionalAuth\`). |
| **User** | Any signed-in account. |
| **Admin** | Custom claim \`role\` of \`admin\` or \`superadmin\`. |

Grant an admin role with:

\`\`\`bash
npm run set:role -- someone@example.com admin
\`\`\`

The role lives in the user's Firebase custom claims and applies after their next
token refresh (the script revokes existing sessions to force this).

### Error responses

| Status | Meaning |
| --- | --- |
| 401 | No token, expired token, revoked token, or malformed token. |
| 403 | Valid token, but the role is insufficient. |
| 404 | Unknown route or missing record. |

## Endpoints

`;

for (const [title, prefix, modPath] of GROUPS) {
  const router = require(path.join(__dirname, modPath));
  const rows = [];
  for (const layer of router.stack) {
    if (!layer.route) continue;
    const methods = Object.keys(layer.route.methods).map((m) => m.toUpperCase()).join(",");
    const chain = layer.route.stack.map((h) => h.handle.name || "anonymous");
    const full = `${prefix}${layer.route.path}`;

    let level = "User";
    if (chain.includes("requireRoleMiddleware")) level = "**Admin**";
    else if (chain.includes("optionalAuth")) level = "Public";
    else if (ANON.has(`${methods} ${full}`)) level = "Anonymous";
    else if (!chain.some((n) => ["requireAuth","requireSelfOrAdminMiddleware"].includes(n)))
      level = "UNGUARDED";

    const upload = chain.includes("multerMiddleware") ? "multipart/form-data" : "application/json";
    rows.push(`| \`${methods}\` | \`${full}\` | ${level} | ${upload} |`);
  }
  if (!rows.length) continue;
  out += `### ${title}\n\n| Method | Path | Access | Body |\n| --- | --- | --- | --- |\n${rows.join("\n")}\n\n`;
}

out += `## Health

\`GET /health\` returns \`{ "status": "ok", "uptime": <seconds> }\` and needs no auth.
Point the platform's health check at it.
`;

fs.writeFileSync(path.join(__dirname, "..", "API.md"), out);
console.log("API.md regenerated");
