/**
 * Mock exam question bank, part 2: tax, law, economics, IT, governance,
 * capital markets, software skills. Same format as part 1.
 */
module.exports = {
  nigerianTax: [
    ["Which body administers federal taxes such as companies income tax and VAT in Nigeria?", ["State Internal Revenue Services", "The federal revenue authority (FIRS / Nigeria Revenue Service)", "Central Bank of Nigeria", "Corporate Affairs Commission"], 1, "Federal taxes are administered by the federal revenue authority; states administer personal income tax of residents."],
    ["Personal income tax of an employee is generally paid to:", ["The state where the employee is resident", "The Federal Government always", "The employer's head office state", "The local government"], 0, "PIT is due to the relevant tax authority of the state of residence."],
    ["PAYE means:", ["Tax paid annually by the employee", "Tax deducted by the employer from pay and remitted", "A tax on company profits", "A capital gains tax"], 1, "Pay As You Earn is withheld at source by employers."],
    ["Withholding tax is best described as:", ["A final tax in all cases", "Tax deducted at source on certain payments, often creditable against the recipient's liability", "A tax on imports", "A penalty"], 1, "WHT is an advance tax collected at source."],
    ["VAT is a tax on:", ["Profits", "Consumption of goods and services", "Salaries", "Property values"], 1, "VAT is an indirect consumption tax collected along the supply chain."],
    ["A taxpayer who disagrees with an assessment should first:", ["Ignore it", "Lodge an objection with the tax authority within the prescribed time", "Go to the Supreme Court", "Pay double"], 1, "Objection to the tax authority comes before appeal to the Tax Appeal Tribunal."],
    ["Capital allowances replace which accounting charge in tax computations?", ["Interest", "Depreciation", "Cost of sales", "Dividends"], 1, "Depreciation is added back and capital allowances are claimed instead."],
    ["An expense is generally deductible for companies income tax when it is:", ["Of a capital nature", "Wholly, exclusively, necessarily and reasonably incurred for the business", "A dividend", "A fine"], 1, "The WREN test for deductibility."],
    ["Tax avoidance differs from tax evasion because avoidance:", ["Is illegal", "Uses lawful arrangements to reduce tax", "Hides income", "Involves false returns"], 1, "Evasion is illegal; avoidance uses the law, though anti-avoidance rules may apply."],
    ["Self-assessment means:", ["The tax authority computes all tax", "The taxpayer computes and files their own liability", "No tax is paid", "Only audits apply"], 1, "Taxpayers file and pay based on their own computations, subject to audit."],
  ],
  advancedTax: [
    ["Transfer pricing rules require related-party transactions to be priced at:", ["Cost", "Arm's length", "Market value only for goods", "Any agreed price"], 1, "The arm's length principle, as in the OECD guidelines."],
    ["A permanent establishment is relevant because it:", ["Exempts a foreign company from tax", "Can create a taxable presence for a foreign company", "Is a type of VAT", "Only applies to individuals"], 1, "Business profits of non-residents are taxable where they have a PE."],
    ["Double taxation relief can be given by:", ["Ignoring foreign income", "Credit for foreign tax paid, or exemption, under treaties or unilateral rules", "Paying tax twice", "Deferring tax indefinitely"], 1, "Credit and exemption methods relieve double taxation."],
    ["Petroleum and extractive operations in Nigeria are taxed under:", ["Only personal income tax", "Specific regimes for petroleum and mining in addition to general rules", "VAT only", "No tax"], 1, "Extractive industries have specific fiscal regimes and royalties."],
    ["A tax audit primarily aims to:", ["Punish taxpayers", "Verify that returns are accurate and complete", "Set tax rates", "Replace self-assessment"], 1, "Audits check compliance; investigations follow suspected fraud."],
    ["Thin capitalisation rules restrict:", ["Dividends", "Interest deductions on excessive related-party debt", "Capital allowances", "VAT refunds"], 1, "They limit interest relief where debt is disproportionate."],
    ["Strategic tax planning should always be:", ["Aggressive", "Lawful, documented and aligned with the business's commercial substance", "Secret", "Based on evasion"], 1, "Planning must have commercial substance and comply with anti-avoidance rules."],
    ["Country-by-country reporting helps tax authorities assess:", ["Local VAT", "Multinationals' global allocation of income and taxes", "Payroll", "Customs duty"], 1, "It is part of the OECD BEPS Action 13 framework."],
    ["A tax investigation differs from a tax audit because it:", ["Is routine", "Follows suspicion of fraud, wilful default or neglect", "Is voluntary", "Covers only VAT"], 1, "Investigations are triggered by suspected evasion."],
    ["Stamp duties are charged on:", ["Profits", "Instruments/documents", "Salaries", "Imports only"], 1, "Stamp duty applies to specified instruments."],
  ],
  ukTax: [
    ["In the UK, the tax year for individuals runs:", ["1 January - 31 December", "6 April - 5 April", "1 April - 31 March", "1 July - 30 June"], 1, "The UK personal tax year starts on 6 April."],
    ["Capital gains tax is charged on:", ["Salary", "Gains on disposal of chargeable assets", "Company profits", "VAT"], 1, "CGT applies to chargeable disposals by individuals."],
    ["Which is an exempt benefit for employees?", ["Company car for private use", "Employer pension contributions to a registered scheme", "Private medical insurance", "Living accommodation (generally)"], 1, "Registered pension contributions by employers are exempt."],
    ["Corporation tax is charged on a company's:", ["Turnover", "Taxable total profits", "Dividends paid", "Share capital"], 1, "Taxable total profits include trading profits, property income and chargeable gains."],
    ["VAT registration becomes compulsory when:", ["A business starts", "Taxable supplies exceed the registration threshold", "Profit exceeds a limit", "Employees are hired"], 1, "Registration is based on taxable turnover."],
    ["Inheritance tax is mainly charged on:", ["Gifts between spouses", "The value of an estate on death and some lifetime transfers", "Salaries", "Company profits"], 1, "IHT applies to chargeable transfers."],
    ["Trading losses of a company can be:", ["Only carried back", "Relieved against current profits, carried back or forward subject to rules", "Ignored", "Paid out as cash always"], 1, "Several loss relief options exist."],
    ["National Insurance contributions are paid by:", ["Only employers", "Employees, employers and self-employed individuals", "Only companies", "Only pensioners"], 1, "Different classes apply to each."],
    ["A company is UK resident if:", ["It trades in the UK", "It is incorporated in the UK or centrally managed and controlled there", "It has UK customers", "It pays UK VAT"], 1, "Incorporation or central management and control."],
    ["Input VAT on business purchases can generally be:", ["Never recovered", "Recovered against output VAT", "Claimed as income", "Paid to suppliers"], 1, "Registered traders reclaim input VAT."],
  ],
  businessLaw: [
    ["The essential elements of a valid contract include offer, acceptance, consideration and:", ["Writing", "Intention to create legal relations", "A lawyer", "Payment in cash"], 1, "Plus capacity and legality."],
    ["An invitation to treat is:", ["An offer", "An invitation to make offers, e.g. goods on display", "Acceptance", "A binding contract"], 1, "Displays and adverts are usually invitations to treat."],
    ["A company is a separate legal entity from its members, as established in:", ["Donoghue v Stevenson", "Salomon v Salomon", "Carlill v Carbolic", "Hadley v Baxendale"], 1, "Salomon v Salomon & Co (1897)."],
    ["Lifting the corporate veil may occur when:", ["A company makes a loss", "The company is used as a sham to evade obligations", "Shares are sold", "Directors change"], 1, "Courts disregard separate personality in cases of fraud or sham."],
    ["In Nigeria, company registration is handled by:", ["SEC", "Corporate Affairs Commission", "CBN", "FIRS"], 1, "CAMA 2020 empowers the Corporate Affairs Commission."],
    ["A condition in a contract is:", ["A minor term", "A major term whose breach allows termination and damages", "An opinion", "A representation"], 1, "Breach of warranty gives damages only."],
    ["Damages for breach of contract aim to:", ["Punish the defendant", "Put the claimant in the position as if the contract had been performed", "Return all money always", "Reward the court"], 1, "Expectation loss, subject to remoteness (Hadley v Baxendale)."],
    ["A partner in a general partnership has:", ["Limited liability", "Unlimited liability for partnership debts", "No authority", "No share of profit"], 1, "General partners are personally liable."],
    ["Agency by estoppel arises when:", ["An agent is appointed in writing", "The principal's conduct makes a third party believe someone is an agent", "A court appoints", "An emergency occurs"], 1, "Apparent (ostensible) authority."],
    ["Negligence requires a duty of care, breach and:", ["A contract", "Damage caused by the breach that is not too remote", "Intention", "A written warning"], 1, "Causation and remoteness complete the tort."],
  ],
  economics: [
    ["If demand is price inelastic, a price increase will:", ["Reduce total revenue", "Increase total revenue", "Not change quantity", "Shift demand"], 1, "Quantity falls proportionately less than price rises."],
    ["Opportunity cost is:", ["Money cost", "The value of the next best alternative forgone", "Fixed cost", "Sunk cost"], 1, "The core economic idea of choice."],
    ["Inflation is:", ["A fall in prices", "A sustained rise in the general price level", "A rise in one price", "Higher wages"], 1, "Measured by indices such as the CPI."],
    ["Monetary policy in Nigeria is set by:", ["Ministry of Finance", "Central Bank of Nigeria", "FIRS", "SEC"], 1, "The CBN's Monetary Policy Committee sets the policy rate."],
    ["A perfectly competitive firm is a:", ["Price maker", "Price taker", "Monopolist", "Oligopolist"], 1, "Many firms, identical products, so no firm influences price."],
    ["GDP measures:", ["Government spending only", "The value of final goods and services produced in an economy in a period", "Exports only", "Money supply"], 1, "Measured by output, income or expenditure approaches."],
    ["Fiscal policy uses:", ["Interest rates", "Government spending and taxation", "Exchange controls only", "Bank reserves"], 1, "Monetary policy uses rates and money supply."],
    ["A normal good is one whose demand:", ["Falls as income rises", "Rises as income rises", "Is unaffected by price", "Is fixed"], 1, "Inferior goods see demand fall as income rises."],
    ["Diminishing marginal returns occur when:", ["All inputs increase", "Adding more of a variable input to fixed inputs yields smaller extra output", "Costs fall", "Demand rises"], 1, "A short-run production concept."],
    ["A devaluation of the naira, other things equal, tends to:", ["Make imports cheaper", "Make exports cheaper to foreign buyers", "Lower inflation", "Increase the value of foreign debt in naira terms less"], 1, "Exports become more competitive; imports dearer."],
  ],
  businessEnvironment: [
    ["PESTEL analysis examines:", ["Internal strengths", "External political, economic, social, technological, environmental and legal factors", "Competitors only", "Cash flow"], 1, "A macro-environment tool."],
    ["Porter's five forces include threat of new entrants, substitutes, buyer power, supplier power and:", ["Inflation", "Competitive rivalry", "Government", "Technology"], 1, "Rivalry among existing competitors."],
    ["A stakeholder with high power and high interest should be:", ["Ignored", "Managed closely (key player)", "Kept informed only", "Kept satisfied only"], 1, "Mendelow's matrix."],
    ["Corporate social responsibility refers to:", ["Maximising short-term profit only", "A company's responsibilities to society beyond legal minimums", "Paying tax", "Internal audit"], 1, "CSR covers ethical, social and environmental responsibilities."],
    ["A tall organisation structure has:", ["Few layers and wide spans", "Many layers and narrow spans of control", "No managers", "Only teams"], 1, "Flat structures have wide spans and few layers."],
    ["Which is a function of management according to Fayol?", ["Planning", "Auditing", "Taxing", "Selling only"], 0, "Plan, organise, command, coordinate and control."],
    ["Money laundering regulations require accountants to:", ["Ignore suspicions", "Report suspicious transactions to the appropriate authority", "Tip off clients", "Only report to the police after trial"], 1, "Reporting to the FIU; tipping off is an offence."],
    ["The main purpose of corporate governance codes is to:", ["Increase tax", "Promote accountability, transparency and protection of stakeholders", "Set prices", "Regulate trade unions"], 1, "E.g. the Nigerian Code of Corporate Governance 2018."],
    ["Maslow's highest need is:", ["Safety", "Self-actualisation", "Esteem", "Social"], 1, "Physiological, safety, social, esteem, self-actualisation."],
    ["An ethical dilemma for an accountant should first be addressed by:", ["Resigning immediately", "Following the organisation's procedures and professional code, then escalating", "Going to the press", "Ignoring it"], 1, "Use internal channels, the code of ethics and professional advice."],
  ],
  governance: [
    ["In a unitary board, independent non-executive directors mainly:", ["Run daily operations", "Provide independent oversight and challenge", "Prepare accounts", "Audit the company"], 1, "NEDs monitor executives and protect shareholders' interests."],
    ["Separating the roles of chairman and CEO helps to:", ["Speed decisions", "Avoid concentration of power", "Cut costs", "Raise capital"], 1, "A key governance recommendation."],
    ["The audit committee should mainly consist of:", ["Executive directors", "Independent non-executive directors", "External auditors", "Shareholders"], 1, "With at least one member with recent financial experience."],
    ["Agency theory concerns conflicts between:", ["Employees and customers", "Owners (principals) and managers (agents)", "Suppliers and banks", "Government and citizens"], 1, "Governance mechanisms reduce agency costs."],
    ["Enterprise risk management involves identifying, assessing and:", ["Ignoring risks", "Responding to and monitoring risks across the organisation", "Transferring all risks", "Only insuring"], 1, "Responses: avoid, reduce, share, accept."],
    ["A company secretary's core duties include:", ["Setting strategy", "Ensuring board procedures and statutory filings are properly handled", "Auditing accounts", "Selling shares"], 1, "Governance, compliance and statutory records."],
    ["Whistleblowing policies protect employees who:", ["Leak to competitors", "Report wrongdoing in good faith", "Break confidentiality for profit", "Refuse work"], 1, "They encourage reporting of misconduct."],
    ["Integrated thinking in strategy means:", ["Only financial targets", "Considering all resources and stakeholders in decisions", "Ignoring risk", "Outsourcing"], 1, "Linked to integrated reporting."],
    ["The AGM gives shareholders the right to:", ["Run the company", "Vote on resolutions such as appointing directors and auditors", "Sign cheques", "Set salaries of all staff"], 1, "Members exercise control through general meetings."],
    ["Stakeholder theory argues that companies should:", ["Serve only shareholders", "Consider the interests of all who affect or are affected by the organisation", "Maximise sales", "Minimise tax"], 1, "Contrast with shareholder primacy."],
  ],
  informationTechnology: [
    ["Which is an input device?", ["Monitor", "Keyboard", "Printer", "Speaker"], 1, "Keyboards enter data; monitors and printers output it."],
    ["A database management system mainly:", ["Designs logos", "Stores, organises and retrieves data", "Sends email", "Prints reports only"], 1, "DBMS software manages structured data."],
    ["Phishing is:", ["A backup method", "Tricking users into revealing information through fake messages", "A firewall", "A programming language"], 1, "A common social-engineering attack."],
    ["Cloud computing provides:", ["Only local storage", "On-demand computing resources over the internet", "Paper records", "Offline software only"], 1, "SaaS, PaaS and IaaS models."],
    ["Data backups primarily protect against:", ["Tax", "Data loss", "Slow internet", "Printing errors"], 1, "Backups allow recovery after failure or attack."],
    ["A firewall:", ["Cools the computer", "Controls network traffic based on security rules", "Speeds up printing", "Stores passwords"], 1, "It filters incoming and outgoing traffic."],
    ["Electronic tax filing and digital taxation aim to:", ["Remove all tax", "Improve compliance, transparency and efficiency", "Replace accountants", "Stop audits"], 1, "E-filing and digital records ease administration and monitoring."],
    ["Two-factor authentication strengthens security by requiring:", ["Two passwords the same", "Something you know plus something you have or are", "Two computers", "Two users"], 1, "E.g. password plus a one-time code."],
    ["Which is an example of system software?", ["Spreadsheet", "Operating system", "Payroll package", "Game"], 1, "Operating systems manage hardware and run applications."],
    ["Nigeria's data protection law is the:", ["Companies Act", "Nigeria Data Protection Act 2023", "Evidence Act", "Cybercrimes Act only"], 1, "The NDPA 2023 governs personal data processing."],
  ],
  quantitative: [
    ["The mean of 2, 4, 6, 8 is:", ["4", "5", "6", "20"], 1, "Sum 20 / 4 = 5."],
    ["The median of 3, 9, 1, 7, 5 is:", ["3", "5", "7", "9"], 1, "Ordered 1, 3, 5, 7, 9 - middle is 5."],
    ["If P(A) = 0.3, the probability of A not happening is:", ["0.3", "0.7", "1.3", "0"], 1, "1 - 0.3."],
    ["Simple interest on N10,000 at 10% for 2 years is:", ["N1,000", "N2,000", "N2,100", "N12,000"], 1, "10,000 x 10% x 2."],
    ["Compound value of N1,000 at 10% after 2 years is:", ["N1,200", "N1,210", "N1,100", "N1,020"], 1, "1,000 x 1.1 x 1.1."],
    ["Standard deviation measures:", ["Central tendency", "Dispersion around the mean", "The mode", "Correlation"], 1, "A measure of spread."],
    ["A correlation coefficient of -1 means:", ["No relationship", "Perfect negative linear relationship", "Weak positive", "Perfect positive"], 1, "Values range from -1 to +1."],
    ["In y = a + bx, b is the:", ["Intercept", "Slope", "Error", "Mean"], 1, "The change in y per unit of x."],
    ["The present value of N1,100 received in one year at 10% is:", ["N1,000", "N1,100", "N990", "N1,210"], 0, "1,100 / 1.1."],
    ["An expected value is:", ["The most likely outcome", "The probability-weighted average of outcomes", "The best outcome", "The median"], 1, "Sum of outcomes x probabilities."],
  ],
  communication: [
    ["The first step in the communication process is:", ["Feedback", "The sender encodes a message", "Decoding", "Noise"], 1, "Sender, encoding, channel, decoding, receiver, feedback."],
    ["Noise in communication means:", ["Loud sounds only", "Anything that distorts or interferes with the message", "Feedback", "The channel"], 1, "Physical, psychological or semantic barriers."],
    ["Which is the best channel for a detailed, formal record?", ["Phone call", "Written report or memo", "Gesture", "Rumour"], 1, "Written communication creates a record."],
    ["Active listening involves:", ["Interrupting", "Paying full attention and giving feedback", "Waiting to speak", "Multitasking"], 1, "Summarising and clarifying show understanding."],
    ["Communication flowing from subordinates to managers is:", ["Downward", "Upward", "Lateral", "Grapevine"], 1, "Upward communication, e.g. reports and feedback."],
    ["The grapevine is:", ["A formal channel", "Informal communication network", "A memo", "A notice board"], 1, "Informal and often fast."],
    ["A report's executive summary should:", ["Repeat the whole report", "Briefly state purpose, findings and recommendations", "Include appendices", "Be written first always"], 1, "It lets busy readers get the key points."],
    ["Non-verbal communication includes:", ["Emails", "Body language and facial expressions", "Letters", "Minutes"], 1, "Often conveys attitude and emotion."],
    ["Minutes of a meeting record:", ["Personal opinions only", "Decisions and actions agreed", "Future plans only", "Gossip"], 1, "An official record of proceedings."],
    ["Clarity in business writing is improved by:", ["Long complex sentences", "Plain words, short sentences and clear structure", "Jargon", "No headings"], 1, "Write for the reader."],
  ],
  management: [
    ["Planning, organising, leading and controlling are:", ["Accounting functions", "Management functions", "Audit stages", "Tax steps"], 1, "The classic management functions."],
    ["Span of control means:", ["The number of subordinates reporting directly to a manager", "The number of departments", "A budget", "A policy"], 0, "Narrow spans mean more layers."],
    ["Herzberg's hygiene factors include:", ["Achievement", "Salary and working conditions", "Recognition", "Growth"], 1, "Hygiene factors prevent dissatisfaction; motivators create satisfaction."],
    ["Delegation means:", ["Giving away responsibility completely", "Assigning authority to a subordinate while retaining accountability", "Firing staff", "Centralising"], 1, "Accountability stays with the manager."],
    ["A SWOT analysis covers strengths, weaknesses, opportunities and:", ["Targets", "Threats", "Taxes", "Teams"], 1, "Internal strengths and weaknesses; external opportunities and threats."],
    ["Leadership style where the leader decides alone is:", ["Democratic", "Autocratic", "Laissez-faire", "Transformational"], 1, "Autocratic leaders centralise decisions."],
    ["Control in management compares:", ["Budgets with tax", "Actual performance with standards and takes corrective action", "Staff with competitors", "Sales with costs only"], 1, "The control cycle."],
    ["A mission statement describes:", ["Detailed budgets", "The organisation's purpose", "Staff rules", "Prices"], 1, "Mission states why the organisation exists."],
    ["Organisational culture is:", ["The dress code only", "Shared values, beliefs and norms", "The org chart", "The pay scale"], 1, "Handy's cultures include power, role, task and person."],
    ["Change resistance is best reduced by:", ["Imposing change without notice", "Communication, participation and support", "Punishment", "Ignoring staff"], 1, "Kotter and Lewin emphasise communication and involvement."],
  ],
  capitalMarkets: [
    ["The apex regulator of Nigeria's capital market is:", ["CBN", "Securities and Exchange Commission (SEC)", "NDIC", "CAC"], 1, "The SEC regulates under the Investments and Securities Act."],
    ["A primary market is where:", ["Existing shares trade", "Securities are issued for the first time", "Only bonds trade", "Currencies trade"], 1, "IPOs and new issues."],
    ["A stockbroker's key duty to clients is:", ["Guaranteeing profits", "Acting in the client's best interest with due care and skill", "Trading for themselves first", "Setting share prices"], 1, "Fiduciary and conduct obligations."],
    ["Insider dealing is:", ["Legal for directors", "Trading on material non-public price-sensitive information", "Normal trading", "Short selling"], 1, "It is prohibited market abuse."],
    ["A bond's coupon is:", ["Its price", "The periodic interest payment", "Its maturity", "Its rating"], 1, "Fixed or floating interest."],
    ["Diversification reduces:", ["Market risk", "Unsystematic (specific) risk", "Inflation", "Interest rates"], 1, "Market risk remains."],
    ["The Central Securities Clearing System (CSCS) mainly:", ["Lists companies", "Clears, settles and holds securities in depository", "Sets interest rates", "Audits brokers"], 1, "Post-trade infrastructure."],
    ["A rights issue offers new shares to:", ["The public", "Existing shareholders in proportion to holdings", "Directors only", "Banks"], 1, "Pre-emption rights."],
    ["Price-earnings ratio is:", ["Share price / EPS", "EPS / price", "Dividend / price", "Profit / sales"], 0, "How much investors pay per naira of earnings."],
    ["Know-your-customer procedures help prevent:", ["Price falls", "Money laundering and fraud", "Dividends", "Listings"], 1, "KYC is part of AML compliance."],
  ],
  excel: [
    ["Which function adds a range of numbers?", ["=COUNT()", "=SUM()", "=ADD()", "=TOTAL()"], 1, "SUM adds values."],
    ["An absolute cell reference is written as:", ["A1", "$A$1", "A$1$", "#A1"], 1, "Dollar signs fix the column and row."],
    ["VLOOKUP searches for a value in:", ["The last row", "The first column of a table", "Any column", "Headers only"], 1, "It returns a value from a specified column in the same row."],
    ["XLOOKUP improves on VLOOKUP because it can:", ["Only search left to right", "Search in any direction and return exact matches by default", "Not handle errors", "Only use numbers"], 1, "It replaces VLOOKUP/HLOOKUP."],
    ["Which function returns a value if a condition is true and another if false?", ["=IF()", "=AND()", "=CHOOSE()", "=MATCH()"], 0, "IF(logical_test, value_if_true, value_if_false)."],
    ["A PivotTable is used to:", ["Draw pictures", "Summarise and analyse large data sets quickly", "Protect sheets", "Write macros"], 1, "Drag fields into rows, columns and values."],
    ["=SUMIF(A:A,\"Lagos\",B:B) returns:", ["Count of Lagos", "Sum of B where A equals Lagos", "Average of B", "An error"], 1, "Conditional sum."],
    ["Conditional formatting:", ["Changes formulas", "Formats cells based on their values or rules", "Sorts data", "Deletes duplicates"], 1, "E.g. highlight values above a threshold."],
    ["Freeze Panes is used to:", ["Lock the file", "Keep headers visible while scrolling", "Stop calculation", "Hide columns"], 1, "Found on the View tab."],
    ["The #DIV/0! error means:", ["Missing file", "A formula divided by zero or an empty cell", "Wrong function name", "Text in formula"], 1, "Wrap with IFERROR if needed."],
  ],
  financialModeling: [
    ["A good financial model separates:", ["Nothing", "Inputs, calculations and outputs", "Only years", "Colours"], 1, "Clear structure makes models auditable."],
    ["Hard-coding numbers inside formulas is:", ["Best practice", "Poor practice; put assumptions in input cells", "Required", "Faster to audit"], 1, "Inputs should be visible and changeable."],
    ["The three core linked statements in a model are:", ["P&L, balance sheet and cash flow", "Budget, forecast, actual", "Sales, costs, tax", "Assets, debt, equity"], 0, "Linked so the balance sheet balances."],
    ["Sensitivity analysis examines:", ["Formatting", "How outputs change when one input changes", "Only best case", "Audit trails"], 1, "Often via data tables."],
    ["Scenario analysis differs because it changes:", ["One input", "Several inputs together to represent a situation", "Nothing", "Only dates"], 1, "Base, upside, downside cases."],
    ["A circular reference in a model typically arises from:", ["Linking interest to average cash that depends on interest", "Using SUM", "Charts", "Formatting"], 0, "Handle with care or a circuit breaker."],
    ["NPV in Excel with cash flows from year 1 onward uses:", ["=NPV(rate, values) plus the time-0 flow separately", "=IRR only", "=PV of the total", "=SUM only"], 0, "Excel's NPV assumes the first value is one period out."],
    ["A checks sheet in a model:", ["Is decoration", "Flags errors like an unbalanced balance sheet", "Stores inputs", "Holds charts"], 1, "Integrity checks catch mistakes early."],
    ["Terminal value in a DCF represents:", ["Year 1 cash flow", "Value of cash flows beyond the explicit forecast period", "Debt", "Tax"], 1, "Perpetuity growth or exit multiple methods."],
    ["Consistent formulas across a row mean:", ["Each cell is different", "The same formula copied across periods", "No formulas", "Only values"], 1, "Easier to review and less error-prone."],
  ],
  businessAnalysis: [
    ["The main role of a business analyst is to:", ["Write all code", "Identify business needs and recommend solutions", "Audit accounts", "Sell products"], 1, "BAs bridge business and technology."],
    ["Requirements elicitation techniques include:", ["Interviews, workshops and observation", "Only guessing", "Taxation", "Audit sampling"], 0, "Also surveys and document analysis."],
    ["A functional requirement describes:", ["How fast the system is", "What the system must do", "The colour", "The budget"], 1, "Non-functional requirements describe qualities like performance."],
    ["A use case describes:", ["Server hardware", "How a user interacts with a system to achieve a goal", "Budget lines", "Staff rota"], 1, "Actors, steps and outcomes."],
    ["MoSCoW prioritisation stands for Must, Should, Could and:", ["Maybe", "Won't (this time)", "Wait", "Want"], 1, "Helps agree scope."],
    ["Gap analysis compares:", ["Two competitors", "Current state with desired future state", "Prices", "Two budgets"], 1, "Identifies what must change."],
    ["A stakeholder map helps to:", ["Draw org charts", "Identify and plan engagement with stakeholders", "Set salaries", "Test code"], 1, "E.g. power/interest grid."],
    ["User acceptance testing is performed by:", ["Developers only", "Business users to confirm the solution meets needs", "Auditors", "Vendors only"], 1, "Final validation before go-live."],
    ["A process map shows:", ["Profits", "Steps and flows of a business process", "Only data", "Legal terms"], 1, "E.g. swimlane diagrams."],
    ["A business case justifies a project by comparing:", ["Colours", "Costs, benefits, risks and options", "Staff names", "Office space"], 1, "Supports investment decisions."],
  ],
  quickbooks: [
    ["The Chart of Accounts in QuickBooks lists:", ["Customers", "All the accounts used to record transactions", "Employees", "Invoices"], 1, "Assets, liabilities, equity, income and expenses."],
    ["An invoice records:", ["A payment to a supplier", "A sale on credit to a customer", "A bank transfer", "A journal"], 1, "Increases accounts receivable."],
    ["Receive Payment is used when:", ["You pay a bill", "A customer pays an invoice", "You record depreciation", "You pay staff"], 1, "Clears the customer's balance."],
    ["A bill in QuickBooks represents:", ["A customer sale", "An amount owed to a supplier", "Cash sale", "A bank fee"], 1, "Increases accounts payable."],
    ["Bank reconciliation in QuickBooks matches:", ["Invoices to customers", "Recorded transactions with the bank statement", "Stock to sales", "Payroll to tax"], 1, "Ensures cash records are complete and correct."],
    ["The Undeposited Funds account holds:", ["Loans", "Payments received but not yet deposited", "Expenses", "Taxes"], 1, "Groups receipts into a single deposit."],
    ["A sales receipt is used for:", ["Credit sales", "Sales paid immediately", "Refunds only", "Purchases"], 1, "No receivable is created."],
    ["The Profit and Loss report shows:", ["Assets and liabilities", "Income and expenses for a period", "Cash only", "Inventory"], 1, "Also called income statement."],
    ["Classes or locations in QuickBooks help to:", ["Lock periods", "Track income and expenses by department or branch", "Delete data", "Pay tax"], 1, "Segment reporting."],
    ["Closing the books in QuickBooks means:", ["Deleting the company", "Setting a closing date to prevent changes to past periods", "Printing reports", "Removing users"], 1, "Protects finalised periods."],
  ],
  sage: [
    ["In Sage 50, customer records are held in:", ["Suppliers", "Customers module", "Nominal ledger only", "Bank"], 1, "Sales ledger."],
    ["The nominal ledger contains:", ["Only bank accounts", "All general ledger accounts", "Customers", "Products"], 1, "Income, expenses, assets, liabilities and capital."],
    ["A sales invoice in Sage posts:", ["Dr Sales, Cr Debtors", "Dr Debtors control, Cr Sales (and VAT)", "Dr Bank, Cr Sales", "No entries"], 1, "Credit sale increases receivables."],
    ["Supplier invoices are entered through:", ["Customers", "Suppliers module", "Bank receipts", "Reports"], 1, "Purchase ledger."],
    ["A journal entry in Sage must:", ["Have only debits", "Have equal debits and credits", "Use one account", "Be approved by HMRC"], 1, "Double entry must balance."],
    ["Bank reconciliation in Sage matches:", ["Stock and sales", "Bank transactions with the statement", "Invoices and orders", "Payroll and tax"], 1, "Confirms bank balance."],
    ["The Trial Balance report lists:", ["Customers", "Balances on all nominal accounts", "Stock levels", "Orders"], 1, "Debits should equal credits."],
    ["Aged debtors analysis shows:", ["Supplier balances", "How long customer balances have been outstanding", "Bank charges", "VAT"], 1, "Helps credit control."],
    ["The VAT return in Sage uses:", ["Only sales", "VAT recorded on sales and purchases", "Payroll", "Assets"], 1, "Output VAT less input VAT."],
    ["Year end in Sage:", ["Deletes data", "Transfers profit/loss to reserves and starts a new financial year", "Pays tax", "Closes the bank account"], 1, "Resets income and expense accounts."],
  ],
};
