/**
 * Mock exam question bank, part 1: accounting, reporting, audit, finance.
 * Each question: [question, [4 options], index of correct option, explanation].
 * Principle-based on purpose - no tax rates or thresholds that change yearly.
 */
module.exports = {
  financialAccounting: [
    ["Which accounting concept requires revenue and related expenses to be recognised in the same period?", ["Going concern", "Accruals (matching)", "Prudence", "Consistency"], 1, "Under the accruals basis, income and the expenses incurred to earn it are recognised in the period they relate to."],
    ["A trial balance that agrees will still fail to reveal which error?", ["A single-entry posting", "A transposition in one account only", "An error of principle", "Omitting one side of a journal"], 2, "Errors of principle post equal debits and credits to the wrong type of account, so the trial balance still balances."],
    ["Closing inventory is understated. What is the effect on gross profit for the year?", ["Overstated", "Understated", "No effect", "Only cost of sales changes"], 1, "Lower closing inventory increases cost of sales, which reduces gross profit."],
    ["Under IAS 16, an item of property, plant and equipment is initially measured at:", ["Fair value", "Cost", "Net realisable value", "Replacement cost"], 1, "IAS 16 requires initial measurement at cost, including directly attributable costs."],
    ["Which of these is a liability?", ["Prepaid rent", "Trade receivables", "Accrued electricity", "Closing inventory"], 2, "An accrual is an expense incurred but not yet paid - an obligation, so a liability."],
    ["The allowance for receivables is increased. The double entry is:", ["Dr Receivables, Cr Profit or loss", "Dr Profit or loss, Cr Allowance for receivables", "Dr Allowance, Cr Receivables", "Dr Cash, Cr Allowance"], 1, "An increase in the allowance is an expense (debit profit or loss) and increases the allowance (credit)."],
    ["Under IAS 2, inventory is measured at:", ["Cost", "Net realisable value", "The lower of cost and net realisable value", "The higher of cost and net realisable value"], 2, "IAS 2 requires the lower of cost and net realisable value, item by item."],
    ["Depreciation is best described as:", ["A way of saving cash to replace assets", "Systematic allocation of an asset's depreciable amount over its useful life", "The fall in an asset's market value", "An estimate of replacement cost"], 1, "Depreciation allocates cost less residual value over the asset's useful life; it is not a cash reserve."],
    ["A bank reconciliation shows unpresented cheques. These are:", ["Added to the bank statement balance", "Deducted from the bank statement balance", "Added to the cash book balance", "Ignored"], 1, "Cheques written but not yet cleared reduce the bank statement balance to agree with the cash book."],
    ["Which statement shows the movement in cash from operating, investing and financing activities?", ["Statement of financial position", "Statement of profit or loss", "Statement of cash flows", "Statement of changes in equity"], 2, "IAS 7 statement of cash flows classifies cash flows into those three activities."],
  ],
  managementAccounting: [
    ["A cost that stays the same in total as activity changes within the relevant range is a:", ["Variable cost", "Fixed cost", "Semi-variable cost", "Step cost"], 1, "Fixed costs are constant in total within the relevant range."],
    ["Contribution per unit is:", ["Selling price less total cost per unit", "Selling price less variable cost per unit", "Fixed cost divided by units", "Profit divided by units"], 1, "Contribution is sales price minus variable cost; it contributes to fixed costs and profit."],
    ["Break-even point in units equals:", ["Fixed costs / contribution per unit", "Variable cost / contribution per unit", "Profit / selling price", "Fixed costs / selling price"], 0, "At break-even total contribution equals fixed costs."],
    ["Under absorption costing, if production exceeds sales, profit compared with marginal costing will be:", ["Lower", "Higher", "The same", "Always zero"], 1, "Some fixed overhead is carried forward in closing inventory, so absorption profit is higher."],
    ["An adverse material price variance means:", ["Less material was used than expected", "Material cost more per unit than standard", "Material was cheaper than standard", "Output was lower than budget"], 1, "The price variance compares actual price with standard price for the quantity bought."],
    ["Which costing method suits a firm producing large numbers of identical units in a continuous flow?", ["Job costing", "Batch costing", "Process costing", "Contract costing"], 2, "Process costing averages costs over identical units produced continuously."],
    ["A flexible budget is one that:", ["Is never changed", "Adjusts cost allowances to the actual level of activity", "Covers several years", "Only includes fixed costs"], 1, "Flexed budgets recognise cost behaviour so variances compare like with like."],
    ["The limiting factor in decision-making is the resource that:", ["Is most expensive", "Restricts output and should be allocated to highest contribution per unit of it", "Has the highest fixed cost", "Is used first"], 1, "Rank products by contribution per unit of the scarce resource."],
    ["A relevant cost for a decision is:", ["A sunk cost", "A future incremental cash flow that differs between options", "A committed cost", "An allocated fixed overhead"], 1, "Only future, incremental cash flows are relevant; sunk and committed costs are not."],
    ["Overhead absorbed exceeds overhead incurred. This is:", ["Under-absorption, a debit to profit", "Over-absorption, a credit to profit", "A price variance", "An error"], 1, "Over-absorbed overhead is added back to profit (credit)."],
  ],
  financialReporting: [
    ["Under IFRS 15, revenue is recognised when:", ["Cash is received", "A performance obligation is satisfied", "The contract is signed", "The invoice is issued"], 1, "IFRS 15 recognises revenue as control of goods or services transfers, satisfying performance obligations."],
    ["Under IFRS 16, a lessee recognises for most leases:", ["An operating expense only", "A right-of-use asset and a lease liability", "A finance receivable", "Nothing until payment"], 1, "IFRS 16 removed the operating lease distinction for lessees except short-term and low-value leases."],
    ["Goodwill arising on acquisition under IFRS 3 is:", ["Amortised over 20 years", "Tested for impairment at least annually", "Written off to reserves", "Revalued yearly"], 1, "Goodwill is not amortised; it is tested for impairment annually (IAS 36)."],
    ["An associate is normally accounted for in consolidated accounts using:", ["Full consolidation", "The equity method", "Cost", "Proportionate consolidation"], 1, "IAS 28 requires the equity method for associates (significant influence)."],
    ["A provision under IAS 37 is recognised when there is a present obligation, a probable outflow and:", ["A contingent asset", "A reliable estimate", "Board approval", "A signed contract"], 1, "All three criteria are needed: obligation, probable outflow, reliable estimate."],
    ["An adjusting event after the reporting period is one that:", ["Occurs after the accounts are issued", "Provides evidence of conditions existing at the reporting date", "Relates to new conditions after the year end", "Is always disclosed only"], 1, "IAS 10 adjusting events give evidence about conditions at the reporting date."],
    ["Under IAS 36, an asset is impaired when its carrying amount exceeds its:", ["Fair value", "Value in use", "Recoverable amount", "Original cost"], 2, "Recoverable amount is the higher of fair value less costs of disposal and value in use."],
    ["Under IFRS 9, a debt instrument held to collect contractual cash flows that are solely principal and interest is measured at:", ["Fair value through profit or loss", "Amortised cost", "Cost", "Fair value through OCI always"], 1, "The business model and SPPI tests lead to amortised cost."],
    ["Deferred tax arises from:", ["Permanent differences", "Temporary differences between carrying amount and tax base", "Tax paid late", "Dividends"], 1, "IAS 12 deferred tax is recognised on temporary differences."],
    ["Non-controlling interest in the consolidated statement of financial position is presented:", ["As a liability", "Within equity, separately from parent equity", "As a deduction from goodwill", "Off balance sheet"], 1, "IFRS 10 presents NCI within equity, separately."],
  ],
  strategicReporting: [
    ["The IASB Conceptual Framework's two fundamental qualitative characteristics are:", ["Comparability and timeliness", "Relevance and faithful representation", "Verifiability and understandability", "Prudence and consistency"], 1, "Relevance and faithful representation are fundamental; the others are enhancing."],
    ["A change in accounting policy under IAS 8 is normally applied:", ["Prospectively", "Retrospectively", "Only to the current year", "Never"], 1, "Policy changes are applied retrospectively unless impracticable; estimate changes are prospective."],
    ["Control over an investee under IFRS 10 requires power, exposure to variable returns and:", ["Majority of shares", "The ability to use power to affect those returns", "Board seats", "Significant influence"], 1, "All three elements define control."],
    ["An entity with a defined benefit plan recognises remeasurement gains and losses in:", ["Profit or loss", "Other comprehensive income", "Retained earnings directly", "Notes only"], 1, "IAS 19 remeasurements go to OCI and are not recycled."],
    ["Integrated reporting (<IR>) focuses on:", ["Tax disclosures", "How an organisation creates value over time using several capitals", "Only financial capital", "Share price"], 1, "<IR> covers financial, manufactured, intellectual, human, social and natural capitals."],
    ["A sale and leaseback that meets IFRS 15 sale criteria results in the seller-lessee recognising:", ["The full gain", "Only the gain relating to rights transferred to the buyer-lessor", "No gain", "A liability for the whole proceeds"], 1, "IFRS 16 limits the gain to the portion of rights transferred."],
    ["Share-based payments settled in equity are measured at:", ["Fair value at grant date", "Fair value at each reporting date", "Intrinsic value", "Nominal value"], 0, "Equity-settled awards use grant-date fair value (IFRS 2)."],
    ["Discontinued operations are presented:", ["Within continuing results", "As a single amount in profit or loss, separately", "Only in the notes", "In OCI"], 1, "IFRS 5 requires a single separate amount for discontinued operations."],
    ["Which is an ethical threat when a director pressures the accountant to hit a profit target?", ["Self-review", "Intimidation", "Advocacy", "Familiarity"], 1, "Pressure from a superior is an intimidation threat."],
    ["When a group loses control of a subsidiary, the retained interest is remeasured to:", ["Carrying amount", "Fair value, with the gain or loss in profit or loss", "Cost", "Nil"], 1, "IFRS 10 remeasures any retained interest to fair value on loss of control."],
  ],
  audit: [
    ["The main objective of an external audit is to:", ["Detect all fraud", "Express an opinion on whether the financial statements give a true and fair view", "Prepare the accounts", "Advise management"], 1, "ISA 200: the auditor gives reasonable assurance and an opinion."],
    ["Audit risk is made up of:", ["Inherent, control and detection risk", "Business and financial risk", "Sampling and non-sampling risk only", "Fraud and error"], 0, "Audit risk = inherent risk x control risk x detection risk."],
    ["Which evidence is generally most reliable?", ["Oral evidence from management", "Evidence obtained directly by the auditor from an external source", "Photocopies from the client", "Internal documents"], 1, "External, auditor-obtained evidence is more reliable (ISA 500)."],
    ["Materiality is:", ["A fixed percentage set by law", "A matter of professional judgement about what would influence users", "Always 5% of profit", "Only about fraud"], 1, "ISA 320: misstatements are material if they could influence users' decisions."],
    ["An auditor who concludes the accounts contain a material but not pervasive misstatement issues:", ["An unmodified opinion", "A qualified opinion", "An adverse opinion", "A disclaimer"], 1, "Material but not pervasive misstatement gives an 'except for' qualified opinion."],
    ["Segregation of duties is an example of:", ["A substantive procedure", "An internal control", "An analytical procedure", "A test of details"], 1, "Separating authorising, recording and custody is a key control."],
    ["A test of controls on purchases would be:", ["Recalculating depreciation", "Checking invoices are authorised before payment", "Circularising receivables", "Attending inventory count for existence"], 1, "Tests of controls check whether controls operated."],
    ["Receivables circularisation mainly tests:", ["Completeness", "Existence", "Valuation of inventory", "Presentation"], 1, "External confirmation provides evidence that receivables exist."],
    ["Going concern doubts that are adequately disclosed lead to:", ["An adverse opinion", "An unmodified opinion with a material uncertainty related to going concern section", "A disclaimer", "No reference"], 1, "ISA 570 adds a separate section; the opinion stays unmodified."],
    ["An auditor's independence is threatened when the firm also prepares the client's accounts because of:", ["Self-interest", "Self-review", "Intimidation", "Advocacy"], 1, "Auditing work you prepared yourself creates a self-review threat."],
  ],
  advancedAudit: [
    ["Forensic accounting is primarily concerned with:", ["Preparing tax returns", "Gathering evidence of fraud or disputes for legal proceedings", "Internal audit only", "Budgeting"], 1, "Forensic work produces evidence suitable for courts and investigations."],
    ["In a forensic investigation, maintaining a chain of custody ensures:", ["Lower fees", "Evidence is admissible and has not been tampered with", "Faster reporting", "Independence"], 1, "Documented handling preserves evidential integrity."],
    ["A key money laundering stage where illicit funds enter the financial system is:", ["Layering", "Placement", "Integration", "Structuring"], 1, "Placement introduces cash into the system; layering obscures; integration returns it."],
    ["Under ISA 600, the group auditor must:", ["Ignore component auditors", "Be involved in the work of component auditors", "Audit every component personally", "Rely fully on component reports"], 1, "The group engagement team directs and evaluates component work."],
    ["A key audit matter (ISA 701) is:", ["Any misstatement", "A matter of most significance in the audit of the current period", "A going concern issue only", "A management letter point"], 1, "KAMs are communicated in the report for listed entities."],
    ["Lowballing refers to:", ["Low materiality", "Quoting a fee well below market to win an audit", "Poor sampling", "Underestimating risk"], 1, "Very low fees threaten quality and independence."],
    ["Which is an indicator of fraud risk (fraud triangle)?", ["Incentive, opportunity and rationalisation", "Materiality, risk and evidence", "Planning, execution and completion", "Price, volume and mix"], 0, "The fraud triangle elements."],
    ["An assurance engagement on prospective financial information gives:", ["Reasonable assurance", "Limited (negative) assurance on assumptions", "No assurance", "Absolute assurance"], 1, "ISAE 3400 gives negative assurance on reasonableness of assumptions."],
    ["Due diligence differs from an audit because it:", ["Always gives an opinion on truth and fairness", "Is tailored to the client's transaction needs", "Is regulated by ISAs", "Is mandatory"], 1, "Due diligence scope is agreed with the client for a transaction."],
    ["Quality management at firm level is governed by:", ["ISA 700", "ISQM 1", "IAS 1", "ISA 505"], 1, "ISQM 1 sets the firm's system of quality management."],
  ],
  financialManagement: [
    ["The net present value decision rule is to accept projects with:", ["IRR below cost of capital", "Positive NPV", "Payback over 5 years", "Negative NPV"], 1, "A positive NPV increases shareholder wealth."],
    ["The internal rate of return is the discount rate at which:", ["NPV is maximised", "NPV equals zero", "Payback is reached", "Profit is zero"], 1, "IRR sets the present value of inflows equal to outflows."],
    ["Working capital cycle equals:", ["Inventory days + receivable days - payable days", "Payable days - receivable days", "Current assets / current liabilities", "Sales / assets"], 0, "The cash operating cycle adds inventory and receivable days and subtracts payable days."],
    ["The weighted average cost of capital weights each source of finance by:", ["Book values only", "Its market value proportion", "Its cost", "Its risk"], 1, "Market values reflect current investor required returns."],
    ["Systematic risk is:", ["Diversifiable", "Market-wide risk that cannot be diversified away", "Specific to one company", "Irrelevant to CAPM"], 1, "CAPM prices only systematic risk (beta)."],
    ["Under CAPM, required return = Rf + beta x:", ["Rf", "(Rm - Rf)", "Rm", "Dividend yield"], 1, "The equity risk premium times beta."],
    ["Interest rate parity predicts forward rates from:", ["Inflation differentials", "Interest rate differentials", "Trade balances", "Growth"], 1, "Forward premium or discount reflects interest rate differences."],
    ["Which is a money market hedge?", ["Buying an option", "Borrowing or depositing in currencies now to fix the exchange rate", "Netting", "Leading and lagging"], 1, "Money market hedges replicate a forward using borrowing and deposits."],
    ["The dividend valuation model values a share as:", ["Next dividend / (ke - g)", "EPS x P/E always", "Book value per share", "Dividend x ke"], 0, "Gordon growth: P0 = D1 / (ke - g)."],
    ["Capital rationing where a firm limits funds itself is called:", ["Hard rationing", "Soft rationing", "Hurdle rationing", "Single-period rationing"], 1, "Internally imposed limits are soft rationing."],
  ],
  advancedFinancialManagement: [
    ["The adjusted present value method separates:", ["Sales and costs", "Base-case NPV and the financing side effects", "Equity and debt holders", "Tax and inflation"], 1, "APV = base-case NPV + PV of financing effects such as tax shields."],
    ["A real option to abandon a project increases its value because:", ["It always generates cash", "It limits downside if outcomes are poor", "It reduces tax", "It removes risk entirely"], 1, "Options add value through flexibility under uncertainty."],
    ["Black-Scholes value of a call rises when:", ["Volatility falls", "Volatility rises", "Time to expiry falls", "Exercise price rises"], 1, "Greater volatility increases option value."],
    ["An interest rate swap is typically used to:", ["Speculate on shares", "Change the interest profile from fixed to floating or vice versa", "Buy currency", "Raise equity"], 1, "Swaps exchange interest payment streams."],
    ["Free cash flow to equity is used to value:", ["The whole firm", "Equity directly", "Debt", "Options"], 1, "FCFE discounted at the cost of equity gives equity value."],
    ["A synergy in an acquisition is:", ["The premium paid", "Extra value where the combined firm is worth more than the parts", "Goodwill impairment", "Transaction cost"], 1, "Revenue, cost or financial synergies create combined value."],
    ["A defensive tactic against a hostile bid is:", ["Poison pill", "Leveraged recapitalisation by the bidder", "Due diligence", "Earn-out"], 0, "Poison pills make the target less attractive."],
    ["Duration measures a bond's:", ["Coupon", "Sensitivity of price to interest rate changes", "Credit rating", "Maturity only"], 1, "Duration is weighted average time to cash flows and interest sensitivity."],
    ["Value at risk states:", ["The maximum possible loss", "The loss not expected to be exceeded at a given confidence level over a period", "Average return", "Beta"], 1, "VaR is a percentile-based loss measure."],
    ["The Modigliani-Miller model with tax suggests firm value rises with gearing because of:", ["Bankruptcy costs", "The tax shield on debt interest", "Higher dividends", "Agency costs"], 1, "Interest is tax deductible, so debt adds a tax shield."],
  ],
  performanceManagement: [
    ["The balanced scorecard perspectives are financial, customer, internal business process and:", ["Tax", "Learning and growth", "Market", "Supplier"], 1, "Kaplan and Norton's four perspectives."],
    ["Target costing starts with:", ["Actual cost plus margin", "A market price less required profit", "Standard cost", "Budgeted overhead"], 1, "Target cost = target price - target profit."],
    ["Activity-based costing assigns overheads using:", ["Direct labour hours only", "Cost drivers of activities", "Units produced", "Sales value"], 1, "ABC traces overheads to activities and then products by cost drivers."],
    ["Return on investment can encourage managers to:", ["Always invest", "Reject projects that lower divisional ROI even if they beat the cost of capital", "Ignore profit", "Increase assets"], 1, "ROI can cause dysfunctional decisions; residual income reduces this."],
    ["Residual income equals:", ["Profit - imputed interest on capital employed", "Profit / capital", "Sales - costs", "Cash - debt"], 0, "RI deducts a capital charge from divisional profit."],
    ["The main purpose of a transfer price is to:", ["Pay tax", "Encourage goal congruence and fair divisional performance measurement", "Set market prices", "Cut costs"], 1, "Good transfer prices align divisional and group interests."],
    ["Zero-based budgeting requires:", ["Last year's budget plus inflation", "Justifying each activity from zero every period", "No budget", "Rolling updates"], 1, "Every cost must be justified afresh."],
    ["A mix variance arises when:", ["Price changes", "Inputs are used in a different proportion from standard", "Output falls", "Wages rise"], 1, "Mix variances measure the effect of changing input proportions."],
    ["Which is a non-financial performance indicator?", ["Gross margin", "Customer complaints per 1,000 orders", "ROCE", "EPS"], 1, "Quality and customer measures are non-financial."],
    ["Throughput accounting treats which cost as the only variable cost?", ["Labour", "Materials", "Overheads", "Depreciation"], 1, "Throughput = sales - material costs."],
  ],
  publicSector: [
    ["IPSAS are issued by:", ["IASB", "IPSASB", "FRC Nigeria", "IFAC Council"], 1, "The International Public Sector Accounting Standards Board issues IPSAS."],
    ["The Consolidated Revenue Fund in Nigeria is primarily governed by:", ["The Companies Act", "The Constitution and Finance (Control and Management) Act", "IFRS", "Tax laws only"], 1, "The Constitution establishes the CRF; public finance laws govern it."],
    ["Appropriation of public funds requires approval by:", ["The Accountant-General", "The legislature", "The Auditor-General", "The Central Bank"], 1, "Only the legislature appropriates funds through an Appropriation Act."],
    ["Accrual-basis IPSAS differs from cash basis because it recognises:", ["Only cash receipts", "Transactions when they occur, not when cash moves", "Only budget figures", "No liabilities"], 1, "Accrual accounting records events when they occur."],
    ["The Treasury Single Account aims to:", ["Increase bank charges", "Consolidate government cash for control and visibility", "Replace budgets", "Privatise revenue"], 1, "TSA unifies government accounts under the Treasury."],
    ["The Auditor-General reports to:", ["The President only", "The legislature", "The Minister of Finance", "The Accountant-General"], 1, "Audit reports on public accounts go to the legislature."],
    ["Value for money covers economy, efficiency and:", ["Equity", "Effectiveness", "Expense", "Earnings"], 1, "The three Es of VFM audits."],
    ["A virement is:", ["A new tax", "Transfer of funds between budget heads with approval", "An audit query", "A loan"], 1, "Virement moves provision between heads within limits."],
    ["Recurrent expenditure mainly covers:", ["Roads and buildings", "Salaries and running costs", "Loans to states", "Investments"], 1, "Capital expenditure covers long-term assets."],
    ["The Fiscal Responsibility Act in Nigeria mainly seeks to:", ["Set tax rates", "Promote prudent management of public resources and debt", "Regulate banks", "Govern audits of companies"], 1, "It sets fiscal rules and transparency requirements."],
  ],
};
